### ISSUE TITLE
Week 2: How old are you??

### ISSUE THREAD

**Issue by ganning127** [ganning127/demo#25]
Week 2 Step 8 ⬤⬤⬤⬤⬤⬤⬤⬤ | 🕐 Estimated completion: 5-10 minutes
### ✅ Task:
**Modify your Azure Function so that it texts the user back with a song.**
- [ ] ***1:*** Retrieve song url from a JSON object 
  ```js
  const songs = {"GenZ":"https://open.spotify.com/track/0SIAFU49FFHwR3QnT5Jx0k?si=1c12067c9f2b4fbf", 
  "GenY":"https://open.spotify.com/track/1Je1IMUlBXcx1Fz0WE7oPT?si=a04bbdf6ec4948b9", 
  "GenX":"https://open.spotify.com/track/4Zau4QvgyxWiWQ5KQrwL43?si=790d9e3ef2ed408d", 
  "BabyBoomers":"https://open.spotify.com/track/4gphxUgq0JSFv2BCLhNDiE?si=1abb329f2dc24f50", 
  "Unknown":"https://open.spotify.com/track/5ygDXis42ncn6kYG14lEVG?si=84b49b41d09d4d11"}
  ```
- [ ] ***2:*** Use `${}` to quickly insert strings
- [ ] ***3:*** Return the url with a personalized message in the body of the request formatted like
```
We guessed you're part of this generation: [insert generation]! Happy listening! [song link]`
```
- [ ] ***4:*** Commit your updated code to `song4u/index.js` in the `song4u` branch, and only merge the pull request when the bot approves your changes! 

### 🚧 Test Your Work
To test your work, try texting a **jpg** image to your Twilio number (with a face!). You should receive a text back that **contains the required message format.**

Example:
```
Sent from your Twilio trial account - We guessed you're part of this generation: GenZ! Happy listening! https://open.spotify.com/track/0SIAFU49FFHwR3QnT5Jx0k?si=1c12067c9f2b4fbf
```

### Working with JSON
JSON has **keys** and **values**. In our case, the generation is the **key**, and the url is the **value.**

See if you can determine the url with this syntax:
```js
let value = json_object[key]
```

### Shortcuts with Strings
You might be used to **concatenating strings and variables** like this:
```js
let string = "Hello " + name
```
That can get tiring, though. Try this syntax:
```js
let string = `Hello ${name}`
```

**Comment by ganning127** [comment]
closed via oauth
